<button class="btn btn-success" onclick="patient_identity_route()">Identity-Form</button>
<button class="btn btn-success" onclick="patient_contact_route()">Contact-Form</button>
<button class="btn btn-success" onclick="patient_choice_route()">Choice-Form</button>
<button class="btn btn-success" onclick="patient_employer_route()">Employer-Form</button>
<button class="btn btn-success" onclick="patient_stats_route()">Stats-Form</button>
<button class="btn btn-success" onclick="patient_guardian_route()">Guardian-Form</button>
<button class="btn btn-success" onclick="patient_primary_route()">primary-Form</button>
<button class="btn btn-success" onclick="patient_secondary_route()">secondary-Form</button>
<button class="btn btn-success" onclick="patient_tertiary_route()">tertiary-Form</button>